# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macOS-10.13' # For Windows, use 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: XamariniOS@2
  inputs:
    solutionFile: 'UtMobileApp.iOS/UtMobileApp.iOS.csproj'
    configuration: '$(buildConfiguration)'
    packageApp: true
    buildForSimulator: false
    runNugetRestore: true